name: fetchly
description: Fetchly provides a streamlined and user-friendly approach to
  harnessing the power of Dio within your Flutter applications.
version: 0.1.1
homepage: https://github.com/ashtav/fetchly

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  ansicolor: ^2.0.2
  dio: ^5.3.2
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
